import React from 'react';
import { View, Text, StyleSheet, ScrollView, BackHandler } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { Colors, Typography, Spacing, Radii, FontFamily } from '../constants/Theme';
import { AuthStackParamList } from '../types';
import AuthProgress from '../components/AuthProgress';
import BottomAction from '../components/BottomAction';

type Props = NativeStackScreenProps<AuthStackParamList, 'Disclaimer'>;

const DisclaimerScreen: React.FC<Props> = ({ navigation }) => {
  const handleDecline = () => {
    BackHandler.exitApp();
  };

  return (
    <SafeAreaView style={styles.safe}>
      <AuthProgress currentStep={3} totalSteps={3} />
      <View style={styles.container}>
        <View style={styles.header}>
          <Text style={styles.title}>Mental Health{'\n'}Disclaimer</Text>
          <Text style={styles.subtitle}>
            Please read before continuing. This app is not a substitute for professional care.
          </Text>
        </View>
        <View style={styles.card}>
          <ScrollView contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false}>
            <Text style={styles.cardTitle}>DISCLAIMER</Text>
            <Text style={styles.cardTextCentered}>
              This app is designed for personal reflection and journaling. It is not intended to
              provide medical, psychological, legal, or professional advice.
            </Text>
            <Text style={styles.sectionHeader}>Not a Substitute for Professional Care</Text>
            <Text style={styles.cardText}>
              Content you write or insights generated by the app should not be used as a replacement
              for professional diagnosis, treatment, or guidance. If you are experiencing distress,
              mental health challenges, or a crisis, seek help from a qualified professional or local
              support services.
            </Text>
            <Text style={styles.sectionHeader}>Personal Responsibility</Text>
            <Text style={styles.cardText}>
              You are solely responsible for how you interpret and use anything written or suggested
              within the app. Reflections, prompts, or summaries are meant to support thinking — not
              to make decisions for you.
            </Text>
            <Text style={styles.sectionHeader}>No Emergency Use</Text>
            <Text style={styles.cardText}>
              This app is not monitored and is not suitable for emergencies. If you are in immediate
              danger or feel at risk of harming yourself or others, contact local emergency services
              immediately.
            </Text>
          </ScrollView>
        </View>
      </View>
      <BottomAction
        onBack={handleDecline}
        onNext={() => navigation.navigate('LegalAgreement')}
      />
    </SafeAreaView>
  );
};

export default DisclaimerScreen;

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.background },
  container: { flex: 1, paddingHorizontal: Spacing.xl, paddingTop: Spacing.xl, paddingBottom: Spacing.sm },
  header: { alignItems: 'center', marginBottom: Spacing.xl },
  title: { fontFamily: FontFamily.serif, fontSize: 28, fontWeight: '700', color: Colors.textPrimary, textAlign: 'center', lineHeight: 36, marginBottom: Spacing.md },
  subtitle: { ...Typography.body, color: Colors.textPrimary, textAlign: 'center' },
  card: { flex: 1, backgroundColor: Colors.surface, borderRadius: Radii.lg, padding: Spacing.lg, shadowColor: Colors.black, shadowOffset: { width: 0, height: Spacing.xxs }, shadowOpacity: 0.05, shadowRadius: Spacing.sm - 2, elevation: 3 },
  scrollContent: { paddingBottom: Spacing.xl },
  cardTitle: { fontFamily: FontFamily.serif, fontSize: 18, fontWeight: '700', color: Colors.primaryDark, textAlign: 'center', marginBottom: Spacing.sm },
  cardTextCentered: { ...Typography.caption, color: Colors.textPrimary, textAlign: 'center', marginBottom: Spacing.lg },
  sectionHeader: { ...Typography.caption, fontWeight: '700', color: Colors.textPrimary, marginBottom: Spacing.xxs },
  cardText: { ...Typography.caption, color: Colors.textSecondary, marginBottom: Spacing.lg },
});
